export const styles = {
  page: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  greenBackground: {
    width: "100%",
    height: "536px",
    backgroundColor: "#00CBA1",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  greenBackgroundImage: {
    width: "302px",
    height: "36px",
  },
  container: {
    width: "525px",
    height: "276px",
    // fontFamily: "Pretendard-Regular",
    fontFamily: "Noto Sans KR",
  },
  title: {
    fontSize: "18px",
    fontWeight: "600",
    marginTop: "40px",
    marginBottom: "20px",
  },
  dataContainer: {
    width: "100%",
    height: "154px",
    border: "1px solid #F5F5F7",
    borderRadius: "15px",
  },
  dataTitle: {
    width: "100%",
    height: "35px",
    backgroundColor: "#F5F5F7",
    borderTopLeftRadius: "14px",
    borderTopRightRadius: "14px",
    paddingLeft: "18px",
    paddingTop: "10px",
  },
  dataTitle_text: {
    fontSize: "10px",
    fontWeight: "600",
  },
  dataContent: {
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    width: "100%",
    height: "100%",
    paddingLeft: "18px",
    paddingTop: "10px",
    paddingRight: "18px",
  },
  copyright: {
    width: "100%",
    height: "29.5px",
    backgroundColor: "#F5F5F7",
  },

  // Table Content styles

  table: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: "10px",
    width: "224.5",
    height: "20px",
  },
  tableTitle: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "37px",
    height: "100%",
  },
  tableTitle_text: {
    fontSize: "8px",
    fontWeight: "500",
  },
  tableContent: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "168.5px",
    height: "100%",
  },
  tableContent_text: {
    fontSize: "8px",
    fontWeight: "300",
  },
  //   mainPageHeaderText: {
  //     color: "#1D1D1F",
  //     fontSize: "19px",
  //     fontWeight: "400",
  //   },
  //   mainPageGradientText: {
  //     backgroundClip: "linear-gradient(#01af9c, #00e6a5)",
  //     color: "#00CBA1",
  //     // webkitBackgroundClip: "text",
  //     // backgroundClip: "text",
  //     // webkitTextFillColor: "transparent",
  //     fontSize: "19px",
  //     fontWeight: "400",
  //   },
  //   mainPageText: {
  //     color: "#6E6E73",
  //     fontSize: "8px",
  //     fontWeight: "400",
  //     marginBottom: "12px",
  //     marginTop: "12px",
  //   },
  //   mainPageContent: {
  //     display: "flex",
  //     flexDirection: "row",
  //     gap: "7px",
  //     alignItems: "center",
  //     justifyContent: "center",
  //   },
  //   mainPageContent_boxOne: {
  //     flex: "1",
  //     display: "flex",
  //     textAlign: "center",
  //     padding: "11px",
  //     border: "0.3px solid grey",
  //     borderRadius: "5px",
  //     // height: "170px",
  //   },
  //   mainPageContent_boxOne_atSign: {
  //     color: "#6E6E73",
  //     fontSize: "4.3px",
  //   },
  //   mainPageContent_boxTwo: {
  //     flex: "2",
  //     display: "flex",
  //     flexDirection: "row",
  //     gap: "5px",
  //     padding: "11px",
  //     height: "170px",
  //     border: "0.3px solid grey",
  //     borderRadius: "5px",
  //   },
  //   mainPageContent_boxTwo_content: {
  //     display: "flex",
  //     // justifyContent: "center",
  //     alignItems: "center",
  //     width: "100%",
  //     height: "100%",
  //     color: "#6E6E73",
  //     fontSize: "9px",
  //   },
  //   sliderTitleContainer: {
  //     width: "100%",
  //     marginTop: "15.5px",
  //     marginBottom: "9px",
  //     display: "flex",
  //     justifyContent: "start",
  //   },
  //   sliderTitle: {
  //     color: "#00CBA1",
  //     fontSize: "7.5px",
  //     fontWeight: "400",
  //   },
  //   sliderContainer: {
  //     width: "100%",
  //     display: "flex",
  //     justifyContent: "start",
  //   },

  //   sliderContent: {
  //     width: "100%",
  //     fontSize: "5.2px",
  //     marginBottom: "4.6px",
  //   },
  //   sliderContent_text: {
  //     display: "flex",
  //     flexDirection: "row",
  //     justifyContent: "space-between",
  //     color: "1D1D1F",
  //     width: "100%",
  //     // backgroundColor: "red",
  //   },
  //   sliderContent_slider: {
  //     width: "100%",
  //     height: "6.2px",
  //     backgroundColor: "#F5F5F7",
  //     borderRadius: "5px",
  //     marginTop: "3px",
  //   },
  //   sliderContent_slider_color: {
  //     display: "flex",
  //     flexDirection: "row",
  //     alignItems: "center",
  //     justifyContent: "flex-end",
  //     borderRadius: "5px",
  //     backgroundColor: "#00CBA1",
  //   },
  //   sliderContent_slider_circle: {
  //     display: "flex",
  //     justifyContent: "center",
  //     alignItems: "center",
  //     width: "13px",
  //     height: "13px",
  //     border: "0.5px solid #00CBA1",
  //     borderRadius: "50%",
  //     backgroundColor: "white",
  //   },
  //   sliderContent_slider_circle_label: {
  //     display: "flex",
  //     justifyContent: "center",
  //     alignItems: "center",
  //     width: "8px",
  //     height: "8px",
  //     backgroundColor: "#00CBA1",
  //     borderRadius: "50%",
  //   },
  //   sliderContent_slider_circle_label_text: {
  //     fontSize: "5.2px",
  //     color: "white",
  //   },
  //   sliderContent_TestDate: {
  //     marginTop: "13px",
  //     alignSelf: "flex-start",
  //     color: "#6E6E73",
  //     fontSize: "3.7px",
  //   },
};
