export const styles = {
  main: {
    width: "100%",
    height: "100%",
    fontFamily: "Noto Sans KR",
  },
  title: {
    marginTop: "20px",
    fontWeight: "500",
    fontSize: "18px",
  },

  // first container
  firstContainer: {
    width: "100%",
    height: "226px",
    marginTop: "40px",
  },
  firstContainer_title: {
    fontSize: "10px",
    fontWeight: "500",
  },
  firstContainer_text: {
    marginTop: "10px",
    fontSize: "9.5px",
    fontWeight: "300",
    textAlign: "justify",
  },
  firstContainer_content: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    height: "139px",
    marginTop: "20px",
  },
  firstContainer_content_box: {
    height: "100%",
    width: "242.5px",
    backgroundColor: "#F5F5F7",
    borderRadius: "10px",
    padding: "12px",
  },
  firstContainer_content_box_title: {
    fontWeight: "500",
    fontSize: "10px",
  },
  firstContainer_content_box_text: {
    fontWeight: "300",
    fontSize: "9.5px",
    marginTop: "10px",
    // textAlign: "justify",
  },

  // second container
  secondContainer: {
    width: "100%",
    height: "128px",
    marginTop: "40px",
  },
  secondContainer_title: {
    fontSize: "10px",
    fontWeight: "500",
  },
  secondContainer_text: {
    fontSize: "9.5px",
    fontWeight: "300",
    textAlign: "justify",
    marginTop: "10px",
  },
  secondContainer_content: {
    display: "flex",
    alignItems: "center",
    width: "100%",
    height: "41px",
    marginTop: "20px",
  },
  secondContainer_content_gradient: {
    position: "relative",
    width: "490px",
    height: "10px",
    marginTop: "5px",
    borderRadius: "100px",
  },
  secondContainer_content_gradient_color: {
    width: "100%",
    height: "100%",
    borderRadius: "100px",
    overflow: "hidden",
  },
  secondContainer_content_gradient_circle: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    top: "-5px",
    left: "15%",
    width: "20px",
    height: "20px",
    borderRadius: "45px",
    border: "1px solid #00E6A5",
    backgroundColor: "#FFFFFF",
  },
  secondContainer_content_gradient_circle_content: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "12.73px",
    height: "12.73px",
    borderRadius: "100px",
    backgroundColor: "#00E6A5",
    fontSize: "8px",
    fontWeight: "700",
    color: "#FFFFFF",
  },
  secondContainer_content_gradient_border: {
    position: "absolute",
    left: "30%",
    height: "100%",
    borderLeft: "1px dashed #FFFFFF",
  },
  secondContainer_content_scale: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: "5px",
    marginTop: "10px",
    width: "490px",
    height: "15px",
  },
  secondContainer_content_scale_percentage: {
    fontSize: "8px",
    fontWeight: "300",
    color: "#8E8E93",
  },
  secondContainer_content_scale_line: {
    position: "relative",
    width: "42px",
    height: "0.5px",
    backgroundColor: "#8E8E93",
  },
  secondContainer_content_scale_line_arrowLeft: {
    position: "absolute",
    left: "0",
    top: "-2.2px",
    width: "5px",
    height: "5px",
    transform: "rotate(-45deg)",
    borderLeft: "0.5px solid #8E8E93",
    borderTop: "0.5px solid #8E8E93",
  },
  secondContainer_content_scale_line_arrowRight: {
    position: "absolute",
    right: "0",
    top: "-2.2px",
    width: "5px",
    height: "5px",
    transform: "rotate(45deg)",
    borderRight: "0.5px solid #8E8E93",
    borderTop: "0.5px solid #8E8E93",
  },
  secondContainer_content_scale_level: {
    fontSize: "9px",
    fontWeight: "500",
    color: "#8E8E93",
  },

  // third container
  thirdContainer: {
    width: "100%",
    height: "233px",
    marginTop: "40px",
    fontFamily: "Noto Sans KR",
  },
  thirdContainer_title: {
    fontSize: "10px",
    fontWeight: "500",
  },
  thirdContainer_text: {
    fontSize: "9.5px",
    fontWeight: "300",
    marginTop: "10px",
  },
  thirdContainer_content: {
    display: "flex",
    flexDirection: "row",
    // alignItems: "space-between",
    justifyContent: "space-between",
    marginTop: "20px",
    width: "100%",
    height: "146px",
  },
  thirdContainer_content_table: {
    height: "100%",
    width: "242px",
  },
  thirdContainer_content_table_title: {
    fontSize: "10px",
    fontWeight: "500",
  },
  thirdContainer_content_table_content: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    width: "100%",
    // height: "100%",
    marginTop: "10px",
  },

  // Table component styles
  table: {
    width: "74.17px",
    backgroundColor: "#F5F5F7",
    borderRadius: "5px",
    padding: "0 5px 0 5px",
  },
  table_title: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "21px",
    fontSize: "8px",
    fontWeight: "500",
    borderBottom: "0.75px solid #515154",
  },
  table_text: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "20px",
    fontSize: "8px",
    fontWeight: "300",
    borderTop: "0.75px solid #D2D2D7",
  },
};
